##Plot4.
##Across the United States, how have emissions from coal combustion-related sources changed from 1999-2008?

##read files, this is where we need the SCC
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")


##Stage 1: get the right data====================
##from SCC, find the coal combustion related sources. Get their SCC code used in NEI - we'll use those to subset NEI.
##The best bet is column EI.Sector 
##find the unique fuel type SCC column 4, and from there extract the ones with Coal
##there are 59 unique EI.Sector, from which 3 with coal: Fuel Comb - Electric Generation - Coal, Fuel Comb - Industrial Boilers, ICEs - Coal and Fuel Comb - Comm/Institutional - Coal
e
##move the dataframe into a matrix, for easier manipulation (at least for me )
matrixSCC<-as.matrix(SCC)

##subset it to only the rows where EI.Sector (column 4) has one of the coal
coal<-subset(matrixSCC, matrixSCC[, 4] == "Fuel Comb - Electric Generation - Coal" | matrixSCC[, 4] == "Fuel Comb - Comm/Institutional - Coal" | matrixSCC[, 4] == "Fuel Comb - Industrial Boilers, ICEs - Coal")

##get the SCC field from matrixSCC, as this is going to be the key to subset NEI
codesForNEI<-coal[, 1]

##now subset NEI by these codes
coalNEI<-subset(NEI, as.character(NEI$SCC) %in% codesForNEI)

##subsetting by years, to use in some calculations
y99<-subset(coalNEI, coalNEI$year == "1999")
y02<-subset(coalNEI, coalNEI$year == "2002")
y05<-subset(coalNEI, coalNEI$year == "2005")
y08<-subset(coalNEI, coalNEI$year == "2008")

##data for the first plot, that will show the average emissions by year
mmData<-data.frame(year = c("1999", "2002", "2005", "2008"), 
                   means = c(mean(y99$Emissions), mean(y02$Emissions), mean(y05$Emissions), mean(y08$Emissions)),
                   medians = c(median(y99$Emissions), median(y02$Emissions), median(y05$Emissions), median(y08$Emissions)))

##new data frame that gets the SCC codes, their Source Type and the Emissions in one place <- for the 3rd plot
dSCC<-data.frame(code = coal[, 1], SourceType = coal[, 4])
dcoalNEI <-data.frame(code = coalNEI$SCC, Emissions = coalNEI$Emissions, year = coalNEI$year)
dataForPlot<-merge(dSCC, dcoalNEI, by = "code")

##rename the long SourceTypeValues
# Fuel Comb - Electric Generation - Coal => Electric Generation
# Fuel Comb - Industrial Boilers, ICEs - Coal => Industrial Boilers, ICEs
# Fuel Comb - Comm/Institutional - Coal => Comm/Institutional
dataForPlot$SourceType <- gsub("^(Fuel Comb -)", "", dataForPlot$SourceType, perl = TRUE)
dataForPlot$SourceType <- gsub("( - Coal)", "", dataForPlot$SourceType, perl = TRUE)

###plot it =============================
##i'll do 3 plots:  
##one that show the mean per year to underline the trends
##one that shows the overall changes across years (approximate using a linear model)
##one that shows the details of changes by types of emissions sources

##open the png device
png(file = "plot4.png", width=1100, height = 960)

##averages plot
plot1 = ggplot(mmData, aes(year, means)) + labs(title = "Average of emissions across US")+geom_point(aes(color = year, size = 10))+labs(y = "Average value of emissions")+geom_line(aes(group=1))

##overall emissions plot
plot2 = qplot(year, Emissions, data = coalNEI, color = year, main = "Changes of emissions across US", method="lm", geom = c("point", "smooth"))
##plot2<- ggplot(coalNEI, aes(year, Emissions)) + labs(title = "Changes of emissions generated by coal-combustion sources, across US") + geom_line()

##emissions split by groups of Source Types
plot3 = qplot(year, Emissions, data = dataForPlot, facets=.~SourceType, color = year, main = "Changes of emissions across US, by type of emission source", method="lm", geom = c("point", "smooth"))

grid.arrange(plot2, plot1, plot3, ncol=1, main = "Emissions generated by coal-combustion sources")


##close png device
dev.off()
